"""Research artifact lifecycle helpers.

The worker stays dependency-free in v0. It generates reproducible script,
Markdown report, and notebook skeleton artifacts from the CSV profile rather
than executing arbitrary analysis code.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def write_analysis_script(profile_path: Path, output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    profile = json.loads(profile_path.read_text(encoding="utf-8"))
    source_path = profile["source_path"]
    output_path = output_dir / f"{profile_path.stem}.analysis.py"
    output_path.write_text(
        "\n".join(
            [
                '"""Reproducible CSV inspection script generated by Research Worker."""',
                "",
                "from __future__ import annotations",
                "",
                "import csv",
                "from pathlib import Path",
                "",
                f"INPUT = Path({source_path!r})",
                "",
                "with INPUT.open('r', encoding='utf-8-sig', newline='') as handle:",
                "    reader = csv.DictReader(handle)",
                "    rows = list(reader)",
                "    columns = reader.fieldnames or []",
                "",
                "print({'row_count': len(rows), 'column_count': len(columns), 'columns': columns})",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return output_path


def write_markdown_report(profile_path: Path, privacy_report_path: Path, output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    profile = json.loads(profile_path.read_text(encoding="utf-8"))
    privacy = json.loads(privacy_report_path.read_text(encoding="utf-8"))
    output_path = output_dir / f"{profile_path.stem}.report.md"
    lines = [
        "# Data Profile Report",
        "",
        f"- Source: `{profile['source_path']}`",
        f"- Rows: {profile['row_count']}",
        f"- Columns: {profile['column_count']}",
        f"- Duplicate rows: {profile['duplicate_rows']}",
        f"- Sensitive columns: {privacy['sensitive_column_count']}",
        f"- Cloud model requires approval: {str(privacy['cloud_model_requires_approval']).lower()}",
        "",
        "## Columns",
        "",
        "| Column | Missing | Privacy | Outliers |",
        "| --- | ---: | --- | ---: |",
    ]
    for column in profile["columns"]:
        lines.append(
            f"| {column['column_name']} | {column['missing_count']} | "
            f"{column['privacy_class']} | {column['outlier']['outlier_count']} |"
        )
    lines.append("")
    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path


def write_notebook(profile_path: Path, report_path: Path, output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    profile = json.loads(profile_path.read_text(encoding="utf-8"))
    report = report_path.read_text(encoding="utf-8")
    output_path = output_dir / f"{profile_path.stem}.ipynb"
    notebook: dict[str, Any] = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": report.splitlines(keepends=True),
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "from pathlib import Path\n",
                    "import csv\n",
                    f"input_path = Path({profile['source_path']!r})\n",
                    "with input_path.open('r', encoding='utf-8-sig', newline='') as handle:\n",
                    "    rows = list(csv.DictReader(handle))\n",
                    "len(rows)\n",
                ],
            },
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "pygments_lexer": "ipython3"},
            "researchcode": {
                "artifact_kind": "notebook",
                "source_profile": str(profile_path),
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    output_path.write_text(json.dumps(notebook, indent=2, sort_keys=True), encoding="utf-8")
    return output_path
