#!/usr/bin/env python3
"""Run all current non-destructive project checks."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path


COMMANDS = [
    ["python3", "scripts/validate_kernel_schemas.py"],
    ["python3", "scripts/claudecode_gap_check.py"],
    ["python3", "scripts/validate_event_sequence.py", "docs/prototypes/event_log_replay/coding_task_sequence.jsonl"],
    ["python3", "scripts/prototype_patch_validator.py", "eval/fixtures/patch"],
    ["python3", "scripts/prototype_command_classifier.py", "eval/fixtures/shell/permission_cases.json"],
    ["python3", "scripts/validate_parser_fixtures.py"],
    ["python3", "scripts/run_parser_eval.py"],
    ["python3", "scripts/run_stream_eval.py"],
    ["python3", "scripts/run_scaffold_eval.py"],
    ["python3", "scripts/run_scaffold_comparison_eval.py"],
    ["python3", "scripts/run_native_profile_promotion_gate.py"],
    ["python3", "scripts/validate_csv_profile_fixture.py"],
    ["python3", "scripts/validate_research_worker_cli.py"],
    ["python3", "scripts/validate_scaffold.py"],
    ["python3", "-m", "unittest", "scripts/test_sqlite_store.py"],
    ["python3", "scripts/sqlite_store.py"],
    ["python3", "scripts/run_eval_harness.py", "--suite", "parser"],
    ["python3", "scripts/run_eval_harness.py", "--suite", "scaffold"],
    ["python3", "scripts/run_eval_harness.py", "--suite", "scaffold_comparison"],
    ["python3", "-m", "py_compile", "scripts/researchcode_agent.py"],
    ["python3", "-m", "unittest", "scripts/test_researchcode_agent.py"],
    ["python3", "-m", "py_compile", "scripts/provider_http_sidecar.py"],
    ["python3", "-m", "unittest", "scripts/test_provider_http_sidecar.py"],
    ["python3", "-m", "unittest", "scripts/test_dev_fixture_bundle.py"],
    ["python3", "scripts/live_deepseek_smoke.py"],
    ["python3", "scripts/run_live_native_eval.py"],
    ["node", "desktop/test_local_api_client.mjs"],
    ["node", "desktop/test_static_mock_contract.mjs"],
    ["node", "desktop/test_desktop_polish_contract.mjs"],
    ["node", "desktop/test_runtime_event_replay.mjs"],
    ["node", "desktop/gui_conversation_quality_smoke.mjs"],
    ["node", "desktop/gui_full_stack_regression.mjs"],
    ["node", "desktop/gui_plan_approval_smoke.mjs"],
    ["node", "desktop/gui_permission_longtask_smoke.mjs"],
    ["node", "desktop/gui_toolstorm_latency_smoke.mjs"],
    ["node", "desktop/gui_argon_longtask_stress.mjs", "--privacy-dry-run", "--provider=deepseek"],
    ["node", "desktop/test_progress_ledger.mjs"],
    ["python3", "-m", "unittest", "workers/research_worker/tests_manifest.py"],
    ["sqlite3", ":memory:", ".read docs/storage/sqlite_schema_v0.sql"],
    ["cargo", "test", "--workspace", "--", "--test-threads=1"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "classify-command", "npm test -- parser"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "prepare-command", "npm install lodash"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "can-transition", "Created", "Planning"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-log", "docs/prototypes/event_log_replay/coding_task_sequence.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "read-file", "README.md"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "search-text", "crates", "ToolSpec"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "git-status", "."],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "agent-tui-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "agent-tui-ui-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "agent-tui-agent-loop-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "agent-tui-resume-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "agent-tui-tool-chain-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "agent-tui-file-write-tool-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "agent-tui-error-boundary-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "provider-tool-schema-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "tool-contract-mediation-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "tool-manifest-doctor-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "unknown-tool-recovery-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "tool-input-repair-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "eventlog-dsml-braces-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "deepseek-content-tool-fallback-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "qwen-tool-mediation-fixture-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "tool-ledger-exactly-once-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "session-terminal-reopen-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "deepseek-reasoning-replay-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "deepseek-natural-visible-answer-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "loop-recovery-directory-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-loop-v2-repeated-tool-recovery-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-loop-v2-tool-error-continuation-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-loop-v2-fastauto-write-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "qwen-native-loop-v2-fastauto-write-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-loop-v2-max-iteration-structured-stop-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-loop-v2-plan-enter-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-loop-v2-ask-user-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "session-memory-continuation-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "deepseek-multi-tool-continuation-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "qwen-tool-continuation-fixture-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "planmode-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "planmode-denies-write-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "subagent-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "agentteam-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "agentteam-messagebus-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "evidence-ledger-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "ultraplan-fixture-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "ultrareview-fixture-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "event-replay-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "runtime-harness-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "event-invariant-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "approval-queue-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "permission-policy-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "runtime-facade-v2-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "runtime-facade-event-delta-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "runtime-facade-ask-user-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "tool-harness-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "patch-set-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "fast-auto-policy-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "research-harness-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "foundation-harness-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "context-bundle-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "compact-context-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "task-contract-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "plan-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "memory-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "multi-agent-policy-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "worktree-plan-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "secret-scan-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-context-policy-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "context-budget-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "repo-map-smoke", "."],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "coding-fixture-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "failure-repair-fixture-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "recorded-model-fixture-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "recorded-patch-fixture-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "recorded-live-response-fixture-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "recorded-agent-loop-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "live-transport-agent-loop-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-agent-loop-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-agent-loop-v2-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-agent-loop-blocked-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-agent-loop-resume-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-agent-loop-external-resume-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-agent-loop-export-pending-package", "/private/tmp/researchcode-native-pending-package"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-agent-loop-resume-pending-package", "/private/tmp/researchcode-native-pending-package", "allow_once"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "recorded-research-loop-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-response-adapter-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-response-normalizer-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "live-model-response-record-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "live-http-transport-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "provider-sidecar-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "provider-health-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "deepseek-sidecar-live-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "qwen-sidecar-live-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "deepseek-reasoning-policy-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "deepseek-stream-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "deepseek-tool-loop-fixture-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "deepseek-tool-result-continuation-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "deepseek-agent-live-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "deepseek-stream-eventlog-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "qwen-stream-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "qwen-stream-eventlog-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "qwen-tool-result-continuation-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-provider-gate-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "model-call-boundary-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "deepseek-request-builder-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "qwen-request-builder-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "live-model-preflight-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "coding-fixture-eventlog", "/private/tmp/researchcode-coding-fixture-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-log", "/private/tmp/researchcode-coding-fixture-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-invariants", "/private/tmp/researchcode-coding-fixture-events.jsonl"],
    ["python3", "scripts/validate_runtime_event_contract.py", "/private/tmp/researchcode-coding-fixture-events.jsonl"],
    ["python3", "scripts/persist_runtime_fixture_sqlite.py", "/private/tmp/researchcode-coding-fixture-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "recorded-live-response-fixture-eventlog", "/private/tmp/researchcode-recorded-live-response-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-log", "/private/tmp/researchcode-recorded-live-response-events.jsonl"],
    ["python3", "scripts/validate_model_event_contract.py", "/private/tmp/researchcode-recorded-live-response-events.jsonl"],
    ["python3", "scripts/persist_runtime_fixture_sqlite.py", "/private/tmp/researchcode-recorded-live-response-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "recorded-agent-loop-eventlog", "/private/tmp/researchcode-recorded-agent-loop-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-log", "/private/tmp/researchcode-recorded-agent-loop-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-invariants", "/private/tmp/researchcode-recorded-agent-loop-events.jsonl"],
    ["python3", "scripts/validate_runtime_event_contract.py", "/private/tmp/researchcode-recorded-agent-loop-events.jsonl"],
    ["python3", "scripts/validate_model_event_contract.py", "/private/tmp/researchcode-recorded-agent-loop-events.jsonl"],
    ["python3", "scripts/persist_runtime_fixture_sqlite.py", "/private/tmp/researchcode-recorded-agent-loop-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "live-transport-agent-loop-eventlog", "/private/tmp/researchcode-live-transport-agent-loop-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-log", "/private/tmp/researchcode-live-transport-agent-loop-events.jsonl"],
    ["python3", "scripts/validate_runtime_event_contract.py", "/private/tmp/researchcode-live-transport-agent-loop-events.jsonl"],
    ["python3", "scripts/validate_model_event_contract.py", "/private/tmp/researchcode-live-transport-agent-loop-events.jsonl"],
    ["python3", "scripts/persist_runtime_fixture_sqlite.py", "/private/tmp/researchcode-live-transport-agent-loop-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-agent-loop-eventlog", "/private/tmp/researchcode-native-agent-loop-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-log", "/private/tmp/researchcode-native-agent-loop-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-invariants", "/private/tmp/researchcode-native-agent-loop-events.jsonl"],
    ["python3", "scripts/validate_runtime_event_contract.py", "/private/tmp/researchcode-native-agent-loop-events.jsonl"],
    ["python3", "scripts/validate_model_event_contract.py", "/private/tmp/researchcode-native-agent-loop-events.jsonl"],
    ["python3", "scripts/persist_runtime_fixture_sqlite.py", "/private/tmp/researchcode-native-agent-loop-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-agent-loop-blocked-eventlog", "/private/tmp/researchcode-native-agent-loop-blocked-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-log", "/private/tmp/researchcode-native-agent-loop-blocked-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-invariants", "/private/tmp/researchcode-native-agent-loop-blocked-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "approval-queue-summary", "/private/tmp/researchcode-native-agent-loop-blocked-events.jsonl"],
    ["python3", "scripts/validate_blocked_permission_event_contract.py", "/private/tmp/researchcode-native-agent-loop-blocked-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-agent-loop-resume-eventlog", "/private/tmp/researchcode-native-agent-loop-resume-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-log", "/private/tmp/researchcode-native-agent-loop-resume-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-invariants", "/private/tmp/researchcode-native-agent-loop-resume-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "event-replay-summary", "/private/tmp/researchcode-native-agent-loop-resume-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-agent-loop-external-resume-eventlog", "/private/tmp/researchcode-native-agent-loop-external-resume-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-log", "/private/tmp/researchcode-native-agent-loop-external-resume-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-invariants", "/private/tmp/researchcode-native-agent-loop-external-resume-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "event-replay-summary", "/private/tmp/researchcode-native-agent-loop-external-resume-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-log", "/private/tmp/researchcode-native-pending-package/resumed_events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-invariants", "/private/tmp/researchcode-native-pending-package/resumed_events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "event-replay-summary", "/private/tmp/researchcode-native-pending-package/resumed_events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "recorded-research-loop-eventlog", "/private/tmp/researchcode-recorded-research-loop-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-log", "/private/tmp/researchcode-recorded-research-loop-events.jsonl"],
    ["python3", "scripts/validate_research_event_contract.py", "/private/tmp/researchcode-recorded-research-loop-events.jsonl"],
    ["python3", "scripts/persist_runtime_fixture_sqlite.py", "/private/tmp/researchcode-recorded-research-loop-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-response-adapter-eventlog", "/private/tmp/researchcode-native-response-adapter-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-log", "/private/tmp/researchcode-native-response-adapter-events.jsonl"],
    ["python3", "scripts/validate_model_event_contract.py", "/private/tmp/researchcode-native-response-adapter-events.jsonl"],
    ["python3", "scripts/persist_runtime_fixture_sqlite.py", "/private/tmp/researchcode-native-response-adapter-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "live-model-response-record-eventlog", "/private/tmp/researchcode-live-response-record-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-log", "/private/tmp/researchcode-live-response-record-events.jsonl"],
    ["python3", "scripts/validate_model_event_contract.py", "/private/tmp/researchcode-live-response-record-events.jsonl"],
    ["python3", "scripts/persist_runtime_fixture_sqlite.py", "/private/tmp/researchcode-live-response-record-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "deepseek-sidecar-live-eventlog", "/private/tmp/researchcode-deepseek-sidecar-live-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-log", "/private/tmp/researchcode-deepseek-sidecar-live-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "qwen-sidecar-live-eventlog", "/private/tmp/researchcode-qwen-sidecar-live-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-log", "/private/tmp/researchcode-qwen-sidecar-live-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-agent-loop-sidecar-live-eventlog", "deepseek", "/private/tmp/researchcode-native-deepseek-sidecar-loop-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-log", "/private/tmp/researchcode-native-deepseek-sidecar-loop-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-agent-loop-sidecar-live-eventlog", "qwen", "/private/tmp/researchcode-native-qwen-sidecar-loop-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-event-log", "/private/tmp/researchcode-native-qwen-sidecar-loop-events.jsonl"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "validate-compatible-provider-sample"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "compatible-provider-request-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "list-tools"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "tool-execution-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "artifact-store-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "command-output-artifact-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "run-safe-command-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "model-adapter-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-prompt-smoke", "deepseek"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "native-prompt-smoke", "qwen"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "model-transcript-artifact-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "research-worker-sidecar-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "research-package-install-policy-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "tool-call-parser-smoke"],
    ["cargo", "run", "-q", "-p", "researchcode-cli", "--", "classify-qwen-output", "{\"deployment\":{\"model\":\"Qwen2-7B\"},\"tool_calls\":[{\"name\":\"file.read\",\"arguments\":{\"path\":\"src/parser.ts\"}}]}"],
]


def main() -> int:
    for path in [
        Path("eval/fixtures/deepseek/parser_golden.json"),
        Path("eval/fixtures/qwen/parser_golden.json"),
    ]:
        print(f"==> parse {path}")
        json.loads(path.read_text(encoding="utf-8"))
    for command in COMMANDS:
        printable = " ".join(command)
        print(f"==> {printable}")
        completed = subprocess.run(command, check=False)
        if completed.returncode != 0:
            print(f"command failed: {printable}", file=sys.stderr)
            return completed.returncode
    print("all checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
